"""
Formularios RRHH del asistente documental (F3.0.4c).

Mixin con los 10 constructores de formulario EXTRAÍDOS VERBATIM desde
`_WizardDocumentoFiscal` (gui/gestion_usuarios.py). Comportamiento idéntico: los
métodos resuelven helpers y estado vía `self` (instancia del wizard, que aporta
_mk_inp/_lbl_s/_p2_scroll/_card_ly/_save_p2/etc. por MRO). Dependencias de módulo
runtime-only (_CIAN/_BORDE/_wz_tr) importadas diferidas al final (anti-ciclo).
"""

from datetime import datetime  # noqa: F401  (igual que gui/gestion_usuarios)

from PyQt6.QtCore import Qt  # noqa: F401
from PyQt6.QtWidgets import (  # noqa: F401
    QHBoxLayout,
    QLabel,
    QScrollArea,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from src.utils.i18n import tr  # noqa: F401


class WizardFormsRRHHMixin:
    """Constructores de formularios RRHH (verbatim). Se mezcla en _WizardDocumentoFiscal."""

    def _p1_worker(self):
        label = self._doc_label()
        lbl = QLabel(tr("cfg.wz_worker_title", default="Datos del trabajador  ·  {label}", label=label))
        lbl.setStyleSheet(f"color:{_CIAN};font-family:'Segoe UI';font-weight:900;font-size:13px;")
        self._card_ly.addWidget(lbl)

        scroll = QScrollArea(); scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet(self._scroll_ss())
        inner = QWidget(); inner.setStyleSheet("background:transparent;")
        il = QVBoxLayout(inner); il.setContentsMargins(0, 0, 16, 0); il.setSpacing(8)

        il.addWidget(self._lbl_s(tr("cfg.wz_f_nombre", default="Nombre completo:")))
        self._inp_nombre = self._mk_inp(tr("cfg.wz_ph_nombre", default="Nombre y apellidos del trabajador"))
        il.addWidget(self._inp_nombre)

        row_nif_nac = QHBoxLayout(); row_nif_nac.setSpacing(8)
        col_nif = QVBoxLayout()
        col_nif.addWidget(self._lbl_s(tr("cfg.wz_f_nif", default="NIF / NIE:")))
        self._inp_nif = self._mk_inp(tr("cfg.wz_ph_idfiscal", default="Identificación fiscal"))
        col_nif.addWidget(self._inp_nif)
        col_nac = QVBoxLayout()
        col_nac.addWidget(self._lbl_s(tr("cfg.wz_f_fnac", default="Fecha de nacimiento:")))
        self._inp_fnac = self._mk_inp(tr("cfg.wz_ph_ddmmaaaa", default="DD/MM/AAAA"))
        col_nac.addWidget(self._inp_fnac)
        row_nif_nac.addLayout(col_nif); row_nif_nac.addLayout(col_nac)
        il.addLayout(row_nif_nac)

        row_ss_nac = QHBoxLayout(); row_ss_nac.setSpacing(8)
        col_ss = QVBoxLayout()
        col_ss.addWidget(self._lbl_s(tr("cfg.wz_f_ss", default="Nº Seguridad Social:")))
        self._inp_ss = self._mk_inp(tr("cfg.wz_ph_afiliacion", default="Número de afiliación"))
        col_ss.addWidget(self._inp_ss)
        col_nacion = QVBoxLayout()
        col_nacion.addWidget(self._lbl_s(tr("cfg.wz_f_nacion", default="Nacionalidad:")))
        self._inp_nacionalidad = self._mk_inp(tr("cfg.wz_ph_nacion", default="Ej: ESPAÑOLA"))
        col_nacion.addWidget(self._inp_nacionalidad)
        row_ss_nac.addLayout(col_ss); row_ss_nac.addLayout(col_nacion)
        il.addLayout(row_ss_nac)

        # Nivel formativo + su código (inline)
        row_nf = QHBoxLayout(); row_nf.setSpacing(8)
        c_form = QVBoxLayout(); c_form.addWidget(self._lbl_s(tr("cfg.wz_f_nivelform", default="Nivel formativo:")))
        self._inp_formativo = self._mk_inp(tr("cfg.wz_ph_nivelform", default="Ej: ESO, Bachillerato, FP, Grado…"))
        c_form.addWidget(self._inp_formativo)
        c_cnf = QVBoxLayout(); c_cnf.addWidget(self._lbl_s(tr("cfg.wz_f_cod_nivelform", default="Cód. nivel formativo:")))
        self._inp_cod_nivelform = self._mk_inp("Ej: 34"); c_cnf.addWidget(self._inp_cod_nivelform)
        row_nf.addLayout(c_form); row_nf.addLayout(c_cnf); il.addLayout(row_nf)

        il.addWidget(self._lbl_s(tr("cfg.wz_f_titulacion", default="Titulación (si procede):")))
        self._inp_titulacion = self._mk_inp(tr("cfg.wz_ph_titulacion", default="Ej: Grado en ADE, FP Comercio…"))
        il.addWidget(self._inp_titulacion)

        # Municipio de domicilio + su código (inline)
        row_mun = QHBoxLayout(); row_mun.setSpacing(8)
        c_mun = QVBoxLayout(); c_mun.addWidget(self._lbl_s(tr("cfg.wz_f_municipio", default="Municipio de domicilio:")))
        self._inp_municipio = self._mk_inp(tr("cfg.wz_ph_municipio", default="Ciudad de residencia"))
        c_mun.addWidget(self._inp_municipio)
        c_cmu = QVBoxLayout(); c_cmu.addWidget(self._lbl_s(tr("cfg.wz_f_cod_municipio", default="Cód. municipio:")))
        self._inp_cod_municipio = self._mk_inp("Ej: 08298"); c_cmu.addWidget(self._inp_cod_municipio)
        row_mun.addLayout(c_mun); row_mun.addLayout(c_cmu); il.addLayout(row_mun)

        # Provincia + su código (inline)
        row_prov = QHBoxLayout(); row_prov.setSpacing(8)
        c_prov = QVBoxLayout(); c_prov.addWidget(self._lbl_s(tr("cfg.wz_f_provincia", default="Provincia:")))
        self._inp_provincia = self._mk_inp(tr("cfg.wz_ph_provincia", default="Provincia de residencia"))
        c_prov.addWidget(self._inp_provincia)
        c_cpr = QVBoxLayout(); c_cpr.addWidget(self._lbl_s(tr("cfg.wz_f_cod_provincia", default="Cód. provincia:")))
        self._inp_cod_provincia = self._mk_inp("Ej: 08"); c_cpr.addWidget(self._inp_cod_provincia)
        row_prov.addLayout(c_prov); row_prov.addLayout(c_cpr); il.addLayout(row_prov)

        # País + su código (inline)
        row_pais = QHBoxLayout(); row_pais.setSpacing(8)
        c_pais = QVBoxLayout(); c_pais.addWidget(self._lbl_s(tr("cfg.wz_f_pais", default="País:")))
        self._inp_pais = self._mk_inp(tr("cfg.wz_ph_pais", default="ESPAÑA")); self._inp_pais.setText("ESPAÑA")
        c_pais.addWidget(self._inp_pais)
        c_cpa = QVBoxLayout(); c_cpa.addWidget(self._lbl_s(tr("cfg.wz_f_cod_pais", default="Cód. país (ej. 724):")))
        self._inp_cod_pais = self._mk_inp("Ej: 724"); c_cpa.addWidget(self._inp_cod_pais)
        row_pais.addLayout(c_pais); row_pais.addLayout(c_cpa); il.addLayout(row_pais)

        # Código postal + Sexo
        row_cp_sx = QHBoxLayout(); row_cp_sx.setSpacing(8)
        c_cp = QVBoxLayout(); c_cp.addWidget(self._lbl_s(tr("cfg.wz_f_cp", default="Código postal:")))
        self._inp_cp = self._mk_inp(tr("cfg.wz_ph_cp", default="Ej: 08500"))
        c_cp.addWidget(self._inp_cp)
        c_sexo = QVBoxLayout(); c_sexo.addWidget(self._lbl_s(tr("cfg.wz_f_sexo", default="Sexo:")))
        self._combo_sexo = self._mk_combo(["—", "MUJER", "HOMBRE", "OTRO"])
        c_sexo.addWidget(self._combo_sexo)
        row_cp_sx.addLayout(c_cp); row_cp_sx.addLayout(c_sexo); il.addLayout(row_cp_sx)

        # Teléfono + Correo
        row_tel_mail = QHBoxLayout(); row_tel_mail.setSpacing(8)
        c_tel = QVBoxLayout(); c_tel.addWidget(self._lbl_s(tr("cfg.wz_f_telefono", default="Teléfono:")))
        self._inp_telefono = self._mk_inp(tr("cfg.wz_ph_telefono", default="Ej: 600 000 000"))
        c_tel.addWidget(self._inp_telefono)
        c_mail = QVBoxLayout(); c_mail.addWidget(self._lbl_s(tr("cfg.wz_f_email", default="Correo electrónico:")))
        self._inp_email = self._mk_inp(tr("cfg.wz_ph_email", default="correo@ejemplo.com"))
        c_mail.addWidget(self._inp_email)
        row_tel_mail.addLayout(c_tel); row_tel_mail.addLayout(c_mail)
        il.addLayout(row_tel_mail)

        il.addStretch()
        scroll.setWidget(inner)
        self._card_ly.addWidget(scroll, 1)

        br = QHBoxLayout(); br.addStretch()
        bs = self._nav_btn(tr("cfg.nav_next", default="SIGUIENTE  →")); bs.clicked.connect(self._save_p1)
        br.addWidget(bs)
        self._card_ly.addLayout(br)

    def _p2_CONTRATO(self):
        _, subtypes = self.DOCS["CONTRATO"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Modalidad de contrato:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        self._p2_fecha_label(il, "Fecha de inicio:")
        il.addWidget(self._lbl_s("Fecha fin (solo temporal / sustitución / prácticas):"))
        self._inp_fecha_fin = self._mk_inp("DD/MM/AAAA")
        il.addWidget(self._inp_fecha_fin)

        il.addWidget(self._sep_lbl("PUESTO DE TRABAJO"))
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Puesto / Cargo:"))
        self._inp_puesto = self._mk_inp("Ej: Colaborador Tienda, Cajero/a…")
        c1.addWidget(self._inp_puesto)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Grupo profesional:"))
        self._inp_grupo = self._mk_inp("Ej: Grupo 4, Vendedor 2º")
        c2.addWidget(self._inp_grupo)
        row1.addLayout(c1); row1.addLayout(c2)
        il.addLayout(row1)
        il.addWidget(self._lbl_s("Funciones principales:"))
        self._inp_funciones = self._mk_inp("Descripción breve de las funciones")
        il.addWidget(self._inp_funciones)
        il.addWidget(self._lbl_s("Centro de trabajo (registrado en DATOS DE EMPRESA):"))
        self._combo_centro = self._mk_combo_centros()
        il.addWidget(self._combo_centro)
        il.addWidget(self._lbl_s("Representante legal (firmante del contrato):"))
        self._combo_rep = self._mk_combo_representantes()
        il.addWidget(self._combo_rep)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Trabajo a distancia:"))
        self._combo_distancia = self._mk_combo(["NO", "SÍ"])
        c3.addWidget(self._combo_distancia)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Tipo de jornada:"))
        self._combo_jornada = self._mk_combo(["TIEMPO COMPLETO", "TIEMPO PARCIAL"])
        c4.addWidget(self._combo_jornada)
        row2.addLayout(c3); row2.addLayout(c4)
        il.addLayout(row2)
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Horas semanales:"))
        self._inp_horas = self._mk_inp("Ej: 40 / 20")
        c5.addWidget(self._inp_horas)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("Distribución horaria:"))
        self._inp_distribucion = self._mk_inp("Ej: LUNES A DOMINGO")
        c6.addWidget(self._inp_distribucion)
        row3.addLayout(c5); row3.addLayout(c6)
        il.addLayout(row3)

        il.addWidget(self._sep_lbl("RETRIBUCIÓN Y CONTRATO"))
        row4 = QHBoxLayout(); row4.setSpacing(8)
        c7 = QVBoxLayout(); c7.addWidget(self._lbl_s("Salario bruto anual (€):"))
        self._inp_sal = self._mk_inp("Ej: 18000.00")
        c7.addWidget(self._inp_sal)
        c8 = QVBoxLayout(); c8.addWidget(self._lbl_s("Nº de pagas:"))
        self._combo_pagas = self._mk_combo(["12", "14"])
        c8.addWidget(self._combo_pagas)
        row4.addLayout(c7); row4.addLayout(c8)
        il.addLayout(row4)
        row5 = QHBoxLayout(); row5.setSpacing(8)
        c9 = QVBoxLayout(); c9.addWidget(self._lbl_s("Período de prueba:"))
        self._inp_prueba = self._mk_inp("Ej: TRES MESES")
        c9.addWidget(self._inp_prueba)
        c10 = QVBoxLayout(); c10.addWidget(self._lbl_s("Vacaciones:"))
        self._inp_vacaciones = self._mk_inp("Ej: Según Convenio / 23 días hábiles")
        c10.addWidget(self._inp_vacaciones)
        row5.addLayout(c9); row5.addLayout(c10)
        il.addLayout(row5)
        il.addWidget(self._lbl_s("Convenio colectivo aplicable:"))
        self._inp_convenio = self._mk_inp("Ej: Convenio Colectivo del Comercio Textil de Barcelona")
        il.addWidget(self._inp_convenio)

        il.addWidget(self._sep_lbl("ASISTENCIA LEGAL DE LOS TRABAJADORES"))
        il.addWidget(self._lbl_s("Tipo de representación:"))
        self._combo_asist = self._mk_combo([
            "No procede", "Comité de Empresa", "Delegado Sindical",
            "Representación Legal de los Trabajadores",
        ])
        il.addWidget(self._combo_asist)
        row_as1 = QHBoxLayout(); row_as1.setSpacing(8)
        ca1 = QVBoxLayout(); ca1.addWidget(self._lbl_s("Nombre y apellidos:"))
        self._inp_asist_nombre = self._mk_inp("Nombre del representante"); ca1.addWidget(self._inp_asist_nombre)
        ca2 = QVBoxLayout(); ca2.addWidget(self._lbl_s("DNI / NIE:"))
        self._inp_asist_nif = self._mk_inp("Identificación"); ca2.addWidget(self._inp_asist_nif)
        row_as1.addLayout(ca1); row_as1.addLayout(ca2); il.addLayout(row_as1)
        row_as2 = QHBoxLayout(); row_as2.setSpacing(8)
        ca3 = QVBoxLayout(); ca3.addWidget(self._lbl_s("Cargo:"))
        self._inp_asist_cargo = self._mk_inp("Ej: Presidente del comité"); ca3.addWidget(self._inp_asist_cargo)
        ca4 = QVBoxLayout(); ca4.addWidget(self._lbl_s("Organización / sindicato:"))
        self._inp_asist_org = self._mk_inp("Ej: CCOO, UGT…"); ca4.addWidget(self._inp_asist_org)
        row_as2.addLayout(ca3); row_as2.addLayout(ca4); il.addLayout(row_as2)

        il.addWidget(self._sep_lbl("COFINANCIACIÓN / LOGOS INSTITUCIONALES"))
        self._chk_fse = self._mk_check(
            "Contrato cofinanciado — mostrar logos institucionales en la cabecera (FSE+ / UE / Ministerio / SEPE)")
        self._chk_fse.setChecked(True)  # por defecto marcado (modelo SEPE/FSE)
        il.addWidget(self._chk_fse)

        il.addWidget(self._sep_lbl("CLÁUSULAS ADICIONALES (ANEXO)"))
        _clauses = [
            "Prorrateo de pagas extraordinarias",
            "Obligaciones de no competencia desleal (arts. 4.1 y 21.1 ET)",
            "Uso restringido de Internet y correo corporativo",
            "Protección de datos personales (LOPDGDD 3/2018)",
            "Compensación de horas extra con descanso",
            "Interrupción del período de prueba por IT/nacimiento",
            "Vacaciones en días laborables",
            "Obligación de comunicar baja/alta médica de forma inmediata",
        ]
        self._checks_adicionales = []
        for clause_txt in _clauses:
            cb_check = self._mk_check(clause_txt); cb_check.setChecked(True)
            il.addWidget(cb_check); self._checks_adicionales.append((clause_txt, cb_check))
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_NOMINA(self):
        scroll, inner, il = self._p2_scroll()
        self._p2_fecha_label(il, "Mes/período nómina (DD/MM/AAAA):")
        il.addWidget(self._sep_lbl("DEVENGOS"))
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Salario base mensual (€):"))
        self._inp_sal = self._mk_inp("Ej: 1200.00")
        c1.addWidget(self._inp_sal)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Nº de pagas:"))
        self._combo_pagas = self._mk_combo(["12", "14"])
        c2.addWidget(self._combo_pagas)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Plus transporte (€):"))
        self._inp_plus_trans = self._mk_inp("Ej: 50.00")
        c3.addWidget(self._inp_plus_trans)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Plus convenio (€):"))
        self._inp_plus = self._mk_inp("Ej: 30.00")
        c4.addWidget(self._inp_plus)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Nocturnidad (€):"))
        self._inp_noct = self._mk_inp("Ej: 0.00")
        c5.addWidget(self._inp_noct)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("Horas extra (€):"))
        self._inp_he = self._mk_inp("Ej: 0.00")
        c6.addWidget(self._inp_he)
        row3.addLayout(c5); row3.addLayout(c6); il.addLayout(row3)
        row4 = QHBoxLayout(); row4.setSpacing(8)
        c7 = QVBoxLayout(); c7.addWidget(self._lbl_s("Incentivos / Bonus (€):"))
        self._inp_bonus = self._mk_inp("Ej: 0.00")
        c7.addWidget(self._inp_bonus)
        c8 = QVBoxLayout(); c8.addWidget(self._lbl_s("Dietas (€):"))
        self._inp_dietas = self._mk_inp("Ej: 0.00")
        c8.addWidget(self._inp_dietas)
        row4.addLayout(c7); row4.addLayout(c8); il.addLayout(row4)
        il.addWidget(self._sep_lbl("DEDUCCIONES"))
        row5 = QHBoxLayout(); row5.setSpacing(8)
        c9 = QVBoxLayout(); c9.addWidget(self._lbl_s("IRPF (%):"))
        self._inp_irpf = self._mk_inp("Ej: 15.00")
        c9.addWidget(self._inp_irpf)
        c10 = QVBoxLayout(); c10.addWidget(self._lbl_s("SS trabajador (%):"))
        self._inp_ss_pct = self._mk_inp("Ej: 6.35")
        c10.addWidget(self._inp_ss_pct)
        row5.addLayout(c9); row5.addLayout(c10); il.addLayout(row5)
        row6 = QHBoxLayout(); row6.setSpacing(8)
        c11 = QVBoxLayout(); c11.addWidget(self._lbl_s("Anticipos (€):"))
        self._inp_anticipos = self._mk_inp("Ej: 0.00")
        c11.addWidget(self._inp_anticipos)
        c12 = QVBoxLayout(); c12.addWidget(self._lbl_s("Embargos (€):"))
        self._inp_embargos = self._mk_inp("Ej: 0.00")
        c12.addWidget(self._inp_embargos)
        row6.addLayout(c11); row6.addLayout(c12); il.addLayout(row6)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_ALTA(self):
        scroll, inner, il = self._p2_scroll()
        self._p2_fecha_label(il, "Fecha de alta:")
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Tipo de contrato:"))
        self._combo_sub = self._mk_combo(["INDEFINIDO", "TEMPORAL", "FIJO DISCONTINUO", "PARCIAL", "PRÁCTICAS"])
        c1.addWidget(self._combo_sub)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Tipo de jornada:"))
        self._combo_jornada = self._mk_combo(["TIEMPO COMPLETO", "TIEMPO PARCIAL"])
        c2.addWidget(self._combo_jornada)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        il.addWidget(self._lbl_s("Horario de trabajo:"))
        self._inp_distribucion = self._mk_inp("Ej: L-V 09:00-17:00")
        il.addWidget(self._inp_distribucion)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Categoría profesional:"))
        self._inp_puesto = self._mk_inp("Ej: Técnico, Auxiliar…")
        c3.addWidget(self._inp_puesto)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Convenio colectivo:"))
        self._inp_convenio = self._mk_inp("Convenio aplicable")
        c4.addWidget(self._inp_convenio)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        il.addWidget(self._lbl_s("Centro de trabajo:"))
        self._inp_centro = self._mk_inp("Dirección del centro")
        il.addWidget(self._inp_centro)
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Salario bruto anual (€):"))
        self._inp_sal = self._mk_inp("Ej: 18000.00")
        c5.addWidget(self._inp_sal)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("IRPF (%):"))
        self._inp_irpf = self._mk_inp("Ej: 15.00")
        c6.addWidget(self._inp_irpf)
        row3.addLayout(c5); row3.addLayout(c6); il.addLayout(row3)
        il.addWidget(self._lbl_s("Cuenta bancaria IBAN:"))
        self._inp_iban = self._mk_inp("ES00 0000 0000 0000 0000 0000")
        il.addWidget(self._inp_iban)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_BAJA(self):
        _, subtypes = self.DOCS["BAJA"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de baja:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        self._p2_fecha_label(il, "Fecha de efecto de la baja:")
        il.addWidget(self._lbl_s("Motivo (descripción):"))
        self._inp_motivo_baja = self._mk_inp("Descripción del motivo")
        il.addWidget(self._inp_motivo_baja)
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Vacaciones pendientes (días):"))
        self._inp_vac_dias = self._mk_inp("Ej: 5")
        c1.addWidget(self._inp_vac_dias)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Entrega de material empresa:"))
        self._combo_material = self._mk_combo(["SÍ", "NO"])
        c2.addWidget(self._combo_material)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_CERTIFICADO(self):
        _, subtypes = self.DOCS["CERTIFICADO"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de certificado:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        self._p2_fecha_label(il, "Fecha de emisión:")
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Fecha inicio relación laboral:"))
        self._inp_f_inicio_rel = self._mk_inp("DD/MM/AAAA")
        c1.addWidget(self._inp_f_inicio_rel)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Fecha fin relación laboral:"))
        self._inp_f_fin_rel = self._mk_inp("DD/MM/AAAA o EN ACTIVO")
        c2.addWidget(self._inp_f_fin_rel)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Tipo de contrato:"))
        self._combo_jornada = self._mk_combo(["INDEFINIDO", "TEMPORAL", "FIJO DISCONTINUO", "PARCIAL"])
        c3.addWidget(self._combo_jornada)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Grupo de cotización:"))
        self._inp_grupo = self._mk_inp("Ej: Grupo 5")
        c4.addWidget(self._inp_grupo)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Base cotización (€/mes):"))
        self._inp_base_cot = self._mk_inp("Ej: 1500.00")
        c5.addWidget(self._inp_base_cot)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("Base desempleo (€/mes):"))
        self._inp_base_desempleo = self._mk_inp("Ej: 1500.00")
        c6.addWidget(self._inp_base_desempleo)
        row3.addLayout(c5); row3.addLayout(c6); il.addLayout(row3)
        row4 = QHBoxLayout(); row4.setSpacing(8)
        c7 = QVBoxLayout(); c7.addWidget(self._lbl_s("Vacaciones pendientes (días):"))
        self._inp_vac_dias = self._mk_inp("Ej: 0")
        c7.addWidget(self._inp_vac_dias)
        c8 = QVBoxLayout(); c8.addWidget(self._lbl_s("Pagas extras pendientes:"))
        self._combo_pagas_pend = self._mk_combo(["Ninguna", "Proporcional", "Completas"])
        c8.addWidget(self._combo_pagas_pend)
        row4.addLayout(c7); row4.addLayout(c8); il.addLayout(row4)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_CERT_LABORAL(self):
        _, subtypes = self.DOCS["CERT LABORAL"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de certificado:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        self._p2_fecha_label(il, "Fecha de emisión:")
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Cargo / Puesto actual:"))
        self._inp_puesto = self._mk_inp("Ej: Responsable de Tienda")
        c1.addWidget(self._inp_puesto)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Antigüedad (desde DD/MM/AAAA):"))
        self._inp_antiguedad = self._mk_inp("Fecha de incorporación")
        c2.addWidget(self._inp_antiguedad)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        il.addWidget(self._lbl_s("Funciones principales:"))
        self._inp_funciones = self._mk_inp("Descripción de las funciones")
        il.addWidget(self._inp_funciones)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Horario de trabajo:"))
        self._inp_distribucion = self._mk_inp("Ej: L-V 09:00-17:00")
        c3.addWidget(self._inp_distribucion)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Salario bruto anual (€):"))
        self._inp_sal = self._mk_inp("Ej: 18000.00")
        c4.addWidget(self._inp_sal)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_CARTA_DESPIDO(self):
        _, subtypes = self.DOCS["CARTA DESPIDO"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de despido:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Fecha de comunicación:"))
        self._inp_fecha = self._mk_inp(datetime.now().strftime("%d/%m/%Y"))
        self._inp_fecha.setText(datetime.now().strftime("%d/%m/%Y"))
        c1.addWidget(self._inp_fecha)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Fecha de efecto:"))
        self._inp_fecha_efecto = self._mk_inp("DD/MM/AAAA")
        c2.addWidget(self._inp_fecha_efecto)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        il.addWidget(self._lbl_s("Artículo del ET invocado:"))
        self._inp_art_et = self._mk_inp("Ej: Art. 54 ET (disciplinario) / Art. 52 ET (objetivo)")
        il.addWidget(self._inp_art_et)
        il.addWidget(self._lbl_s("Descripción de los hechos:"))
        self._inp_hechos = QTextEdit()
        self._inp_hechos.setPlaceholderText(_wz_tr("Descripción detallada de los hechos imputados…"))
        self._inp_hechos.setMinimumHeight(70); self._inp_hechos.setMaximumHeight(100)
        self._inp_hechos.setStyleSheet(
            f"QTextEdit{{background:#161B22;color:white;border:2px solid {_BORDE};"
            f"border-radius:10px;padding:8px 14px;font-family:'Segoe UI';font-weight:bold;"
            f"font-size:13px;}}QTextEdit:focus{{border-color:{_CIAN};}}"
        )
        il.addWidget(self._inp_hechos)
        il.addWidget(self._sep_lbl("PRECEDENTES"))
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Advertencias previas:"))
        self._combo_advertencias = self._mk_combo(["SÍ", "NO"])
        c3.addWidget(self._combo_advertencias)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Expedientes disciplinarios previos:"))
        self._combo_expedientes = self._mk_combo(["SÍ", "NO"])
        c4.addWidget(self._combo_expedientes)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        il.addWidget(self._sep_lbl("LIQUIDACIÓN"))
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Indemnización (€):"))
        self._inp_indemnizacion = self._mk_inp("Ej: 0.00")
        c5.addWidget(self._inp_indemnizacion)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("Vacaciones pendientes (días):"))
        self._inp_vac_dias = self._mk_inp("Ej: 5")
        c6.addWidget(self._inp_vac_dias)
        row3.addLayout(c5); row3.addLayout(c6); il.addLayout(row3)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_FINIQUITO(self):
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de baja:"))
        self._combo_sub = self._mk_combo(["VOLUNTARIA", "FIN CONTRATO", "DESPIDO", "JUBILACIÓN", "INCAPACIDAD"])
        il.addWidget(self._combo_sub)
        self._p2_fecha_label(il, "Fecha de baja:")
        il.addWidget(self._sep_lbl("CONCEPTOS A LIQUIDAR"))
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Salario bruto mensual (€):"))
        self._inp_sal = self._mk_inp("Ej: 1500.00")
        c1.addWidget(self._inp_sal)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Días trabajados pendientes:"))
        self._inp_dias_pend = self._mk_inp("Ej: 10")
        c2.addWidget(self._inp_dias_pend)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        row2 = QHBoxLayout(); row2.setSpacing(8)
        c3 = QVBoxLayout(); c3.addWidget(self._lbl_s("Vacaciones pendientes (días):"))
        self._inp_vac_dias = self._mk_inp("Ej: 5")
        c3.addWidget(self._inp_vac_dias)
        c4 = QVBoxLayout(); c4.addWidget(self._lbl_s("Pagas extras pendientes:"))
        self._combo_pagas_pend = self._mk_combo(["Proporcional", "Ninguna", "Completas"])
        c4.addWidget(self._combo_pagas_pend)
        row2.addLayout(c3); row2.addLayout(c4); il.addLayout(row2)
        row3 = QHBoxLayout(); row3.setSpacing(8)
        c5 = QVBoxLayout(); c5.addWidget(self._lbl_s("Horas extra pendientes (€):"))
        self._inp_he = self._mk_inp("Ej: 0.00")
        c5.addWidget(self._inp_he)
        c6 = QVBoxLayout(); c6.addWidget(self._lbl_s("Indemnización (€):"))
        self._inp_indemnizacion = self._mk_inp("Ej: 0.00")
        c6.addWidget(self._inp_indemnizacion)
        row3.addLayout(c5); row3.addLayout(c6); il.addLayout(row3)
        il.addWidget(self._lbl_s("Anticipos descontados (€):"))
        self._inp_anticipos = self._mk_inp("Ej: 0.00")
        il.addWidget(self._inp_anticipos)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()

    def _p2_VACACIONES(self):
        _, subtypes = self.DOCS["VACACIONES"]
        scroll, inner, il = self._p2_scroll()
        il.addWidget(self._lbl_s("Tipo de documento:"))
        self._combo_sub = self._mk_combo(subtypes)
        il.addWidget(self._combo_sub)
        row1 = QHBoxLayout(); row1.setSpacing(8)
        c1 = QVBoxLayout(); c1.addWidget(self._lbl_s("Fecha de inicio (DD/MM/AAAA):"))
        self._inp_fecha = self._mk_inp("DD/MM/AAAA")
        c1.addWidget(self._inp_fecha)
        c2 = QVBoxLayout(); c2.addWidget(self._lbl_s("Fecha de fin (DD/MM/AAAA):"))
        self._inp_fecha_fin_vac = self._mk_inp("DD/MM/AAAA")
        c2.addWidget(self._inp_fecha_fin_vac)
        row1.addLayout(c1); row1.addLayout(c2); il.addLayout(row1)
        il.addWidget(self._lbl_s("Responsable / Aprobado por:"))
        self._inp_responsable = self._mk_inp("Nombre del responsable que aprueba/deniega")
        il.addWidget(self._inp_responsable)
        il.addWidget(self._lbl_s("Motivo de rechazo (solo si DENEGACIÓN):"))
        self._inp_motivo_baja = self._mk_inp("Dejar vacío si no aplica")
        il.addWidget(self._inp_motivo_baja)
        self._p2_obs(il); il.addStretch()
        scroll.setWidget(inner); self._card_ly.addWidget(scroll, 1); self._p2_nav()


# ── Dependencias de módulo runtime-only (import diferido: anti-ciclo). ──
from src.gui.gestion_usuarios import _BORDE, _CIAN, _wz_tr  # noqa: E402,F401
