"""
Espacio Conversacional de SOMA — INFRAESTRUCTURA (Fase 1). Solo se prepara la ARQUITECTURA: define
el contrato que implementará el futuro overlay/personaje/conversación (fases posteriores). El kernel
depende de esta abstracción (no de Qt), de modo que la UI se pueda conectar más adelante sin tocar
el núcleo (mismo espíritu Base/Qt del Enterprise Shell).

En esta fase NO se implementa overlay, personaje, animaciones ni conversación: el kernel usa
`EspacioNulo` (no hace nada) hasta que una fase futura registre el espacio real.
"""


class EspacioConversacional:
    """Contrato del Espacio Conversacional. Lo implementará el overlay en una fase posterior."""

    def mostrar(self, *, motivo=None) -> None: ...
    def ocultar(self) -> None: ...
    def mostrar_estado(self, estado: str) -> None: ...
    def mostrar_mensaje_usuario(self, texto: str) -> None: ...
    def mostrar_respuesta(self, texto: str, *, datos=None) -> None: ...
    def mostrar_workspace(self, mision) -> None: ...
    def esta_visible(self) -> bool: ...
    # Propuestas proactivas: en vez de invadir la pantalla, SOMA avisa con un badge (contador) y la
    # pose "proponiendo" (mano levantada). El usuario abre la propuesta al pulsar el personaje.
    def proponer(self, total: int = 1) -> None: ...
    def reset_propuestas(self) -> None: ...


class EspacioNulo(EspacioConversacional):
    """Implementación NO-OP por defecto (Fase 1). No hay UI todavía."""

    def __init__(self):
        self._visible = False

    def mostrar(self, *, motivo=None) -> None:
        self._visible = True

    def ocultar(self) -> None:
        self._visible = False

    def mostrar_estado(self, estado: str) -> None: ...
    def mostrar_mensaje_usuario(self, texto: str) -> None: ...
    def mostrar_respuesta(self, texto: str, *, datos=None) -> None: ...
    def mostrar_workspace(self, mision) -> None: ...
    def proponer(self, total: int = 1) -> None: ...
    def reset_propuestas(self) -> None: ...

    def esta_visible(self) -> bool:
        return self._visible
